<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.2.4" />
        <PackageReference Include="Aspire.RabbitMQ.Client" Version="13.2.4" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.7" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\DTO\DTO.csproj" />
      <ProjectReference Include="..\HammerOgPensel.ServiceDefaults\HammerOgPensel.ServiceDefaults.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Context\Repositories\Bid\" />
    </ItemGroup>

</Project>
